### ISSUE TITLE
Support for older versions? 

### ISSUE THREAD

**Issue by ItsRodrigoAl** [borknbeans/LightweightInventorySorting#1]
by "older" i mean at least 1.20.6 since that version didn't changed too much from 1.21

**Comment by borknbeans** [comment]
I can look into it!

**Comment by borknbeans** [comment]
Backported to 1.20.6 @ItsRodrigoAl 

Download link for modrinth [here](https://modrinth.com/mod/lightweight-inventory-sorting/version/1.1.0-1.20.6)

**Comment by Alasofia** [comment]
Any chance of 1.20.4? This is quickly becoming my favorite sorting mod and I *really* want to use it on an earlier modpack.

Thanks either way, enjoying this and very happy to not have to use IPN!
