### ISSUE TITLE
Keybind not working for Mouse Buttons

### ISSUE THREAD

**Issue by EastRane** [borknbeans/LightweightInventorySorting#13]
Built the mod from the latest sources. Hotkey "R" works well, but for some reason the middle mouse button click (when I set it as hotkey for sorting) does not want to sort the inventory even when there are no conflicts with other mods' keybinds

**Comment by borknbeans** [comment]
I'll look into it. I believe when I create the key one I specify whether it is attached to the mouse or keyboard, maybe I can do both.

**Comment by borknbeans** [comment]
This has been fixed and will be included in the upcoming patch. Thanks for pointing it out
