### ISSUE TITLE
Clicking sort button with item in hand causes server to kick the player.

### ISSUE THREAD

**Issue by straboti** [borknbeans/LightweightInventorySorting#14]
Whenever I click the sort button with an item "selected" (following the mouse), the game freezes and the server kicks me off with `kicked for exceeding packet rate limit`. (paper server, no plugins or mods).

**Comment by borknbeans** [comment]
Ill look into this, thank you!

**Comment by borknbeans** [comment]
This has been fixed and will be included in the upcoming release, thank you!
