### ISSUE TITLE
Remove 'large' image files from distribution?

### ISSUE THREAD

**Issue by PRRB** [borknbeans/LightweightInventorySorting#2]
Hi there.

Thanks for making this mod. Nice and simple and just what I was looking/hoping for!

If I could make one small suggestion, since this is called "Lightweight" mod - then I guess you can remove the "container-image.png" and "inventory-image.png" files from the distribution, if they aren't needed? They are 496KB in total which accounts for around 96% of the total package size.

**Comment by borknbeans** [comment]
Changes done, will be reflected in newest version when that is released.
