### ISSUE TITLE
[Feature] Shortcut

### ISSUE THREAD

**Issue by TQCnoARosto** [borknbeans/LightweightInventorySorting#6]
It would be nice to have a configurable keybind to sort the hovered inventory. Also a toggolable option to whether or not refill hotbar while sorting the inventory.

**Comment by borknbeans** [comment]
Ill look into adding the keybind for sorting. I don't plan to add the refill hotbar option though.

**Comment by borknbeans** [comment]
This is complete, will be added in next version release.
