### ISSUE TITLE
Strange crash after trying to sort an specific double chest

### ISSUE THREAD

**Issue by vico93** [borknbeans/LightweightInventorySorting#8]
During my singleplayer playthrough i noticed that one of my double chests was behaving strangely. When i click the sort button the items of random slot will get picked after that (even the cursor being over the sort button, not in the respective slot).

At first i just ignored this issue, but in the last time the game just froze, requiring me to close the java process via task manager.

Here's part of `latest.log` showing the error: https://gist.github.com/vico93/75d7b0390ef1af213eb29762419330f0

**Comment by borknbeans** [comment]
I'll take a look into it. Thank you for the logs.

**Comment by borknbeans** [comment]
Would you happen to know the contents of the container when this crash occurred?

**Comment by vico93** [comment]
i can send you my whole profile folder if needed (with the save too)

**Comment by borknbeans** [comment]
That wont be necessary, thank you though

**Comment by borknbeans** [comment]
Issues like these are real difficult to narrow down. I have changed some of the comparison logic which should result in the sorting being more stable and resulting in less mess ups. I can't guarantee these crashes are 100% fixed.

Additionally, I have added some logging each time a sort is run which should give us some insight if it does crash again.

**Comment by vico93** [comment]
Yeah i'm suspicious that that can be something related to components since one of things i stored in those chests were maps.

BTW i also tweaked the config adding a delay between actions (i think this is how its called). Slow things a little bit, but maybe it can prevent the crashes i ran into if i press the button too much

**Comment by borknbeans** [comment]
If I had to guess it was the components. I fixed an [issue](https://github.com/borknbeans/LightweightInventorySorting/issues/9) relating that just now. Hopefully that will be resolved in the upcoming version
